// backend/config/mockStore.js
// In-memory mock database store for AI Studio runtime when PostgreSQL is not configured
const bcrypt = require('bcryptjs');

function createMockDatabase() {
  const hash = (pw) => bcrypt.hashSync(pw, 10);

  const users = [
    {
      id: 1,
      email: 'admin@ait.edu.in',
      password_hash: hash('Admin@123'),
      name: 'System Administrator',
      role: 'Admin',
      department: 'Administrative Office',
      staff_id: 'AIT-ADM-001',
      mobile: '+91 98422 10001',
      avatar: '',
      status: 'Active',
      last_login: new Date().toISOString(),
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 2,
      email: 'principal@ait.edu.in',
      password_hash: hash('Principal@123'),
      name: 'Dr. S. K. Sundararajan',
      role: 'Principal',
      department: 'Administrative Office',
      staff_id: 'AIT-PRI-001',
      mobile: '+91 98422 10002',
      avatar: '',
      status: 'Active',
      last_login: new Date().toISOString(),
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 3,
      email: 'dean@ait.edu.in',
      password_hash: hash('Dean@123'),
      name: 'Dr. M. Jayakumar',
      role: 'Dean',
      department: 'Administrative Office',
      staff_id: 'AIT-DEN-001',
      mobile: '+91 98422 10003',
      avatar: '',
      status: 'Active',
      last_login: new Date().toISOString(),
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 4,
      email: 'hod@ait.edu.in',
      password_hash: hash('Hod@123'),
      name: 'Dr. R. Sundaram',
      role: 'HOD',
      department: 'Computer Science & Engineering',
      staff_id: 'AIT-HOD-001',
      mobile: '+91 98422 10004',
      avatar: '',
      status: 'Active',
      last_login: new Date().toISOString(),
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 5,
      email: 'staff@ait.edu.in',
      password_hash: hash('Staff@123'),
      name: 'Priya Sharma',
      role: 'Staff',
      department: 'Computer Science & Engineering',
      staff_id: 'AIT-STF-001',
      mobile: '+91 98422 10005',
      avatar: '',
      status: 'Active',
      last_login: new Date().toISOString(),
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 6,
      email: 'technician@ait.edu.in',
      password_hash: hash('Technician@123'),
      name: 'Ravi Kumar',
      role: 'Technician',
      department: 'Computer Science & Engineering',
      staff_id: 'AIT-TEC-001',
      mobile: '+91 98422 10006',
      avatar: '',
      status: 'Active',
      last_login: new Date().toISOString(),
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 7,
      email: 'monitor@ait.edu.in',
      password_hash: hash('Monitor@123'),
      name: 'System Monitor',
      role: 'Monitor',
      department: 'Administrative Office',
      staff_id: 'AIT-MON-001',
      mobile: '+91 98422 10007',
      avatar: '',
      status: 'Active',
      last_login: new Date().toISOString(),
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ];

  const blocks = [
    { id: 'BLK-001', name: 'S Block', code: 'S-BLK', description: 'School of Computing, CSE & IT Laboratories', last_updated: new Date().toISOString() },
    { id: 'BLK-002', name: 'N Block', code: 'N-BLK', description: 'Engineering Block — Laboratories, HOD Offices & Research Cells', last_updated: new Date().toISOString() },
    { id: 'BLK-003', name: 'W Block', code: 'W-BLK', description: 'Indoor Sports Complex & Gymnasium', last_updated: new Date().toISOString() },
    { id: 'BLK-004', name: 'M Block', code: 'M-BLK', description: 'Mechanical Engineering Workshops & CAD Labs', last_updated: new Date().toISOString() },
    { id: 'BLK-005', name: 'A Block', code: 'A-BLK', description: 'Academic Block — Classrooms, Faculty Rooms & Departments', last_updated: new Date().toISOString() },
    { id: 'BLK-006', name: 'E Block', code: 'E-BLK', description: 'Electrical & Civil Engineering Testing Labs', last_updated: new Date().toISOString() },
    { id: 'BLK-007', name: 'Old Boys Hostel', code: 'OBH', description: 'Senior Boys Student Residence', last_updated: new Date().toISOString() },
    { id: 'BLK-008', name: 'New Boys Hostel', code: 'NBH', description: 'Junior Boys Student Residence & Dining Block', last_updated: new Date().toISOString() },
    { id: 'BLK-009', name: 'Girls Hostel', code: 'GH', description: 'Girls Student Residence & Common Amenities', last_updated: new Date().toISOString() },
  ];

  const rooms = [
    { id: 1, room_number: 'S101', room_name: 'Library', block: 'S Block', floor: 'Ground Floor', department: 'Central Library', capacity: 100, room_type: 'Library', status: 'Active' },
    { id: 2, room_number: 'S103', room_name: 'AI & DS Department', block: 'S Block', floor: 'Ground Floor', department: 'Artificial Intelligence & Data Science', capacity: 40, room_type: 'Office', status: 'Active' },
    { id: 3, room_number: 'S104', room_name: 'Communication Lab', block: 'S Block', floor: 'Ground Floor', department: 'Electronics & Communication', capacity: 50, room_type: 'Laboratory', status: 'Active' },
    { id: 4, room_number: 'S105', room_name: 'Seminar Hall', block: 'S Block', floor: 'Ground Floor', department: 'General', capacity: 200, room_type: 'Seminar Hall', status: 'Active' },
    { id: 5, room_number: 'S201', room_name: 'Computer Lab 4', block: 'S Block', floor: 'First Floor', department: 'Computer Science & Engineering', capacity: 60, room_type: 'Laboratory', status: 'Active' },
    { id: 6, room_number: 'S203', room_name: 'Computer Lab 3', block: 'S Block', floor: 'First Floor', department: 'Computer Science & Engineering', capacity: 60, room_type: 'Laboratory', status: 'Active' },
    { id: 7, room_number: 'S205', room_name: 'CSE Department', block: 'S Block', floor: 'First Floor', department: 'Computer Science & Engineering', capacity: 30, room_type: 'Office', status: 'Active' },
    { id: 8, room_number: 'S208', room_name: 'Server Room', block: 'S Block', floor: 'First Floor', department: 'Information Technology', capacity: 5, room_type: 'Server Room', status: 'Active' },
    { id: 9, room_number: 'N101', room_name: 'HOD EEE', block: 'N Block', floor: 'Ground Floor', department: 'Electrical & Electronics', capacity: 10, room_type: 'Office', status: 'Active' },
    { id: 10, room_number: 'N201', room_name: 'Computing Lab', block: 'N Block', floor: 'First Floor', department: 'General', capacity: 60, room_type: 'Laboratory', status: 'Active' },
  ];

  const departments = [
    { id: 1, name: 'Computer Science & Engineering', description: 'School of Computing' },
    { id: 2, name: 'Information Technology', description: 'IT and Systems' },
    { id: 3, name: 'Artificial Intelligence & Data Science', description: 'AI, ML and Big Data' },
    { id: 4, name: 'Electronics & Communication', description: 'ECE Department' },
    { id: 5, name: 'Electrical & Electronics', description: 'EEE Department' },
    { id: 6, name: 'Mechanical Engineering', description: 'Mechanical Labs and Workshops' },
    { id: 7, name: 'Civil Engineering', description: 'Civil and Structural Labs' },
    { id: 8, name: 'Administrative Office', description: 'Central Administration' },
    { id: 9, name: 'Central Library', description: 'Main Library Complex' },
    { id: 10, name: 'Physical Education', description: 'Sports and Athletics' },
  ];

  const assets = [
    {
      id: 'AIT-CSE-001',
      name: 'Dell OptiPlex 7090 i7 Workstation',
      category: 'Computer',
      chair_type_id: null,
      department: 'Computer Science & Engineering',
      building: 'S Block',
      floor: 'First Floor',
      room_number: 'S201',
      purchase_date: '2024-03-15',
      purchase_cost: 78500,
      vendor: 'Dell India Pvt Ltd',
      warranty_expiry: '2027-03-15',
      condition: 'Good',
      status: 'Active',
      assigned_to: 'Advanced AI & ML Lab',
      assigned_type: 'Lab',
      qr_code_url: '',
      image_url: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?auto=format&fit=crop&w=600&q=80',
      specifications: 'Intel Core i7 11th Gen, 32GB DDR4 RAM, 1TB NVMe SSD, Nvidia RTX 3060 12GB',
      last_inspected: '2026-07-15',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'AIT-CSE-002',
      name: 'Epson EB-2250U WUXGA Projector',
      category: 'Projector',
      chair_type_id: null,
      department: 'Computer Science & Engineering',
      building: 'S Block',
      floor: 'First Floor',
      room_number: 'S205',
      purchase_date: '2023-08-20',
      purchase_cost: 85000,
      vendor: 'Epson India',
      warranty_expiry: '2026-08-20',
      condition: 'Good',
      status: 'Active',
      assigned_to: 'CSE Department Seminar Room',
      assigned_type: 'Department',
      qr_code_url: '',
      image_url: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=600&q=80',
      specifications: '5,000 Lumens Full HD WUXGA Projector, Screen Mirroring, Dual HDMI',
      last_inspected: '2026-07-14',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'AIT-ECE-012',
      name: 'Tektronix Digital Storage Oscilloscope 100MHz',
      category: 'Laboratory Equipment',
      chair_type_id: null,
      department: 'Electronics & Communication',
      building: 'S Block',
      floor: 'Ground Floor',
      room_number: 'S104',
      purchase_date: '2022-11-10',
      purchase_cost: 65000,
      vendor: 'Tektronix India',
      warranty_expiry: '2025-11-10',
      condition: 'Under Maintenance',
      status: 'Under Maintenance',
      assigned_to: 'Communication Systems Lab',
      assigned_type: 'Lab',
      qr_code_url: '',
      image_url: 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=600&q=80',
      specifications: '4-Channel, 1 GS/s sampling, 7-inch WVGA color display, USB host/device',
      last_inspected: '2026-07-28',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'AIT-LIB-004',
      name: 'Godrej Dual-Sided Steel Library Book Stacks',
      category: 'Storage',
      chair_type_id: null,
      department: 'Central Library',
      building: 'S Block',
      floor: 'Ground Floor',
      room_number: 'S101',
      purchase_date: '2023-01-10',
      purchase_cost: 180000,
      vendor: 'Godrej Interio',
      warranty_expiry: '2033-01-10',
      condition: 'Good',
      status: 'Active',
      assigned_to: 'Chief Librarian',
      assigned_type: 'Department',
      qr_code_url: '',
      image_url: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=600&q=80',
      specifications: 'Heavy duty cold rolled steel, powder-coated, holds up to 2500 books',
      last_inspected: '2026-05-18',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'AIT-IT-018',
      name: 'HP LaserJet Enterprise M611dn Printer',
      category: 'Printer',
      chair_type_id: null,
      department: 'Information Technology',
      building: 'S Block',
      floor: 'First Floor',
      room_number: 'S208',
      purchase_date: '2024-01-25',
      purchase_cost: 62000,
      vendor: 'HP World Coimbatore',
      warranty_expiry: '2027-01-25',
      condition: 'New',
      status: 'Active',
      assigned_to: 'IT Department Office',
      assigned_type: 'Department',
      qr_code_url: '',
      image_url: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&w=600&q=80',
      specifications: '65 ppm Monochrome duplex printing, Gigabit Ethernet, 4.3 inch touch screen',
      last_inspected: '2026-07-10',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'AIT-EEE-005',
      name: '3-Phase AC Motor Control Testing Bench',
      category: 'Electrical Equipment',
      chair_type_id: null,
      department: 'Electrical & Electronics',
      building: 'N Block',
      floor: 'Ground Floor',
      room_number: 'N101',
      purchase_date: '2022-04-12',
      purchase_cost: 340000,
      vendor: 'L&T Electrical Solutions',
      warranty_expiry: '2026-04-12',
      condition: 'Damaged',
      status: 'Damaged',
      assigned_to: 'Electrical Machines Lab',
      assigned_type: 'Lab',
      qr_code_url: '',
      image_url: 'https://images.unsplash.com/photo-1581092162384-8987c1d64718?auto=format&fit=crop&w=600&q=80',
      specifications: '5 HP 415V Motor, Torque Sensor, Digital Tachometer, Safety Trip Relays',
      last_inspected: '2026-07-29',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ];

  const maintenance = [
    {
      id: 1,
      asset_id: 'AIT-ECE-012',
      asset_name: 'Tektronix Digital Storage Oscilloscope 100MHz',
      department: 'Electronics & Communication',
      problem: 'Channel 1 waveform distortion and flickering screen backlight during signal generator input.',
      priority: 'High',
      assigned_technician: 'S. Rajesh Kumar',
      estimated_cost: 12500,
      actual_cost: null,
      status: 'In Progress',
      requested_by: 'Prof. M. Malathi',
      request_date: '2026-07-28',
      completed_date: null,
      remarks: 'Awaiting replacement display driver board from Tektronix Coimbatore Service Center.',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 2,
      asset_id: 'AIT-EEE-005',
      asset_name: '3-Phase AC Motor Control Testing Bench',
      department: 'Electrical & Electronics',
      problem: 'Overcurrent safety relay trips immediately upon energizing 415V supply.',
      priority: 'Critical',
      assigned_technician: 'L&T Authorized Engineer',
      estimated_cost: 28000,
      actual_cost: null,
      status: 'Pending',
      requested_by: 'Lab Incharge - EEE',
      request_date: '2026-07-29',
      completed_date: null,
      remarks: 'Safety hazard. Lab usage halted until relay recalibration.',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 3,
      asset_id: 'AIT-CSE-002',
      asset_name: 'Epson EB-2250U WUXGA Projector',
      department: 'Computer Science & Engineering',
      problem: 'Lamp replacement warning indicator blinking orange after 3500 hours of seminar use.',
      priority: 'Medium',
      assigned_technician: 'S. Rajesh Kumar',
      estimated_cost: 8500,
      actual_cost: 8200,
      status: 'Completed',
      requested_by: 'Dr. R. Sundaram',
      request_date: '2026-07-10',
      completed_date: '2026-07-14',
      remarks: 'Original Epson ELPLP95 replacement lamp installed and optical dust filter cleaned.',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ];

  const allocations = [
    {
      id: 1,
      asset_id: 'AIT-CSE-001',
      asset_name: 'Dell OptiPlex 7090 i7 Workstation',
      from_location: 'Central Store Room',
      to_location: 'S Block - Lab 3',
      from_assignee: 'Store Manager',
      to_assignee: 'Advanced AI & ML Lab',
      transferred_by: 'Dr. R. Sundaram',
      date: '2024-03-16',
      reason: 'Initial setup for AI & Machine Learning Specialization Lab.',
    },
    {
      id: 2,
      asset_id: 'AIT-IT-018',
      asset_name: 'HP LaserJet Enterprise M611dn Printer',
      from_location: 'APJ Kalam Block - Room 201',
      to_location: 'S Block - IT Staff Room',
      from_assignee: 'Exam Cell',
      to_assignee: 'IT Department Office',
      transferred_by: 'HOD IT',
      date: '2025-01-10',
      reason: 'Reallocated to IT Dept staff room after Exam Cell equipment upgrade.',
    },
  ];

  const asset_history = [
    {
      id: 1,
      asset_id: 'AIT-CSE-001',
      type: 'Purchase',
      title: 'Asset Purchased',
      description: 'Procured via Dell Direct Order #AIT-PO-2024-88',
      performed_by: 'Purchase Committee',
      date: '2024-03-15',
      cost: 78500,
    },
    {
      id: 2,
      asset_id: 'AIT-CSE-001',
      type: 'Allocation',
      title: 'Assigned to Lab 3',
      description: 'Allocated to AI & Machine Learning Lab under Dr. R. Sundaram',
      performed_by: 'HOD CSE',
      date: '2024-03-16',
      cost: 0,
    },
  ];

  const notifications = [
    {
      id: 1,
      title: 'High Priority Maintenance Required',
      message: '3-Phase AC Motor Control Testing Bench in EEE Lab reported critical relay tripping.',
      type: 'alert',
      category: 'Maintenance Due',
      asset_id: 'AIT-EEE-005',
      recipient_role: 'Monitor',
      is_read: false,
      timestamp: new Date().toISOString(),
    },
    {
      id: 2,
      title: 'Warranty Expiry Alert',
      message: 'Tektronix Oscilloscope warranty expires in 90 days. Check for extension renewal.',
      type: 'warning',
      category: 'Warranty Expired',
      asset_id: 'AIT-ECE-012',
      recipient_role: 'Admin',
      is_read: false,
      timestamp: new Date().toISOString(),
    },
    {
      id: 3,
      title: 'New Asset Registered',
      message: 'Dell OptiPlex 7090 i7 Workstation (AIT-CSE-001) verified and QR tag generated.',
      type: 'success',
      category: 'Asset Added',
      asset_id: 'AIT-CSE-001',
      recipient_role: null,
      is_read: true,
      timestamp: new Date().toISOString(),
    },
  ];

  const audit_logs = [
    {
      id: 1,
      user_id: 1,
      user_email: 'admin@ait.edu.in',
      role: 'Admin',
      department: 'Administrative Office',
      action: 'SYSTEM_STARTUP',
      details: 'System initialized successfully',
      ip_address: '127.0.0.1',
      timestamp: new Date().toISOString(),
      created_at: new Date().toISOString(),
    },
  ];

  const login_history = [];
  const asset_requests = [];
  const vendors = [
    {
      id: 'VND-001',
      name: 'Dell India Pvt Ltd',
      category: 'Computing Hardware',
      contact_person: 'Anand Kumar',
      phone: '+91 98400 11223',
      email: 'enterprise@dell.co.in',
      gstin: '33AAACD1234F1Z5',
      location: 'Coimbatore, Tamil Nadu',
      rating: 4.8,
      status: 'Active',
    },
    {
      id: 'VND-002',
      name: 'Godrej Interio',
      category: 'Institutional Furniture',
      contact_person: 'Senthil Nathan',
      phone: '+91 98430 44556',
      email: 'coimbatore@godrej.com',
      gstin: '33AABCG5678H1Z8',
      location: 'Gandhipuram, Coimbatore',
      rating: 4.6,
      status: 'Active',
    },
  ];

  return {
    users,
    blocks,
    rooms,
    departments,
    assets,
    maintenance,
    allocations,
    asset_history,
    notifications,
    audit_logs,
    login_history,
    asset_requests,
    vendors,
  };
}

module.exports = { createMockDatabase };
